#!/bin/bash

echo "Chrome Extension Testing Guide"
echo "============================"
echo ""
echo "To test your Hello World Sidebar extension in Chrome:"
echo ""
echo "1. Open Chrome and navigate to chrome://extensions/"
echo "2. Enable 'Developer mode' by toggling the switch in the top right corner"
echo "3. Click 'Load unpacked' and select this directory: $(pwd)"
echo "4. Your extension should now appear in the extensions list"
echo "5. Click on the extension icon in the Chrome toolbar to see your Hello World sidebar"
echo ""
echo "To make changes to your extension:"
echo "1. Edit the files as needed"
echo "2. Return to the chrome://extensions/ page"
echo "3. Click the refresh icon on your extension's card to update it"
echo ""
echo "Happy developing!"
